mskcc/smile-messaging-java

- .circleci/config.yml
- .gitignore
- pom.xml
- src/main/java/org/mskcc/cmo/messaging/Gateway.java
- src/main/java/org/mskcc/cmo/messaging/MessageConsumer.java
- src/main/java/org/mskcc/cmo/messaging/NATSConnection.java
- src/main/java/org/mskcc/cmo/messaging/impl/NATSGatewayImpl.java
- src/main/resources/checkstyle.xml
- test/scripts/generate_checkstyle_report.sh
- Integrated circleci
- Updated checkstyle configuration
- Addressed issues reported by checkstyle plugin to pass validation
> Integrate CircleCI, update checkstyle configuration

- src/main/java/org/mskcc/cmo/messaging/Gateway.java
- src/main/java/org/mskcc/cmo/messaging/impl/NATSGatewayImpl.java
- src/main/resources/checkstyle.xml
Work in progress. 
- Some changes to NATS connection implementation
- Updated checkstyle config, no longer need newline separators in method def's 
> NATS connection impl and checkstyle updates

- src/main/java/org/mskcc/cmo/messaging/Gateway.java
- src/main/java/org/mskcc/cmo/messaging/impl/NATSGatewayImpl.java
> Add isConnected() method to messaging Gateway

- pom.xml
- src/main/java/org/mskcc/cmo/messaging/impl/NATSGatewayImpl.java
> Switch to Jackson deserialization library

- pom.xml
- src/main/java/org/mskcc/cmo/messaging/impl/NATSGatewayImpl.java
- src/main/java/org/mskcc/cmo/messaging/impl/StreamingErrorListener.java
> Remove slf4j logging. Use default apache commons

- src/main/java/org/mskcc/cmo/messaging/Gateway.java
- src/main/java/org/mskcc/cmo/messaging/impl/NATSGatewayImpl.java
> Add new connection method for messaging gateway

- src/main/java/org/mskcc/cmo/messaging/impl/NATSPublishingFileUtil.java
> Use human readable date format

- pom.xml
> Update metadb commons version

- src/main/java/org/mskcc/cmo/messaging/impl/NATSGatewayImpl.java
> Fix false error on publishing

- README.md
- src/main/java/org/mskcc/cmo/messaging/impl/JSGatewayImpl.java
> update property names

- src/main/java/org/mskcc/cmo/messaging/Gateway.java
- src/main/java/org/mskcc/cmo/messaging/impl/JSGatewayImpl.java
> Remove stream argument from pub/sub methods

- src/main/java/org/mskcc/cmo/messaging/impl/JSGatewayImpl.java
> Handle InterruptedException as IOException

- src/main/java/org/mskcc/cmo/messaging/impl/JSGatewayImpl.java
Signed-off-by: Divya Madala <71040191+divyamadala30@users.noreply.github.com>
> resolved multiple consumer issue

- pom.xml
> update commit hash for metadb commons dependency

- pom.xml
> update common commit hash

- src/main/java/org/mskcc/cmo/messaging/impl/JSGatewayImpl.java
Signed-off-by: Divya Madala <71040191+divyamadala30@users.noreply.github.com>
> Updating Builder() to handle request-reply

- src/main/java/org/mskcc/cmo/messaging/impl/JSGatewayImpl.java
These changes resolve the issue we were seeing where subscriber message handler were seeing all messages for a stream
and not just the specific topic that they are subscribed to.
Only applies (and is only necessary) for JetStream-managed subscribers.
Messaging Gateway message handler method `.onMethod(....)` checks for a match on the subject the subscriber
is interested in and the subject embedded in the NATS Message object that is being handled.
If these do not match then the message is handled.
> Add nats subject to message header

- pom.xml
> Add param to enable checkstyle check on test directory

- pom.xml
> Update MetaDB commons

- src/main/java/org/mskcc/cmo/messaging/impl/JSGatewayImpl.java
> Minor fix to message filtering by subject logic

- pom.xml
Update MetaDB commons to: 1.1.7.RELEASE
> Messaging Library release: 1.1.4.RELEASE

- src/main/java/org/mskcc/cmo/messaging/impl/JSGatewayImpl.java
Request ID alone is not unique enough to distinguish a message with the request JSON contents
between the concurrent running MetaDB services.
Example: Request filter publishes a messge with request ID as the identifier and
label-generator attempts to publish the message with the same request JSON contents PLUS
the generated cmo sample labels. Since the "Nats-Msg-Id" is the same the cmo-metadb service
will not actually see the message in cases where the publisher, request-filter, label-generator
are all running on the same machine and using the same request ID in the NATS message header.
--
Messages w/matching NATS Msg ID were not being seen by `cmo-metadb` or `consistency-checker` even though the topics that the messages were …
> Make the Nats-Msg-Id more unique for requests

- pom.xml
- Update commons release to 1.2.1.RELEASE
> Update commons release

- .circleci/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- pom.xml
- src/main/java/org/mskcc/cmo/messaging/impl/JSGatewayImpl.java
- Renaming Metadb to SMILE
- Simple refactoring
---
Please follow these checklists to help prevent any unexpected issues from being introduced by the changes in this pull request. If an item does not apply then indicate so by surrounding the line item with `~~` to strikethrough the text. See [basic writing and formatting syntax](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for more information.
**Data checks:** `N/A`
Updates were made to the mocked incoming request data and/or mocked published request data:
**Code checks:**
If no unit tests were updated or added, …
> Renaming Metadb to SMILE

- pom.xml
- Update SMILE commons dependency (JSON comparator fix)
> Update commons - json comparator fix

- src/main/java/org/mskcc/cmo/messaging/impl/JSGatewayImpl.java
- Increases number of attempts for request-reply 
> Increase number of attempts for request-reply

- pom.xml
- src/main/java/org/mskcc/cmo/messaging/Gateway.java
- src/main/java/org/mskcc/cmo/messaging/impl/JSGatewayImpl.java
Updates to support B3 trace propagation.  Should get smile-commons version upgrade.
> Updates to support B3 trace propagation

- pom.xml
- a
- b 
---
Fix # (see https://help.github.com/en/articles/closing-issues-using-keywords)
**Expected behavior**
**Actual behavior**
**Logs, error output, or stacktrace**
**Steps to reproduce the behavior**
**Tasks**
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at. 
---
Please follow these checklists to help prevent any unexpected issues from being introduced by the changes in this pull request. If an item does not apply then indicate so by surrounding the line item with `~~` to strikethrough the text. See [basic writing and formatting syntax](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/bas …
> Update to commons version with otel changes

- .circleci/config.yml
- jitpack.yml
- pom.xml
- a
- b 
---
Fix # (see https://help.github.com/en/articles/closing-issues-using-keywords)
**Expected behavior**
**Actual behavior**
**Logs, error output, or stacktrace**
**Steps to reproduce the behavior**
**Tasks**
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at. 
---
Please follow these checklists to help prevent any unexpected issues from being introduced by the changes in this pull request. If an item does not apply then indicate so by surrounding the line item with `~~` to strikethrough the text. See [basic writing and formatting syntax](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/bas …
> Origin update java

- pom.xml
- updates smile-commons to 2.1.0.RELEASE
- updates maven-checkstyle to 3.6.0
> Update checkstyle and smile-commons versions
